name: Integration Tests
on:
  push:
    branches:
      - '**' # every branch
      - '!stage*' # exclude branches beginning with stage
  pull_request:
    branches:
      - '**' # every branch
      - '!stage*' # exclude branches beginning with stage
jobs:
  CI:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        matlab_version: ["R2019a"]
        matlab_license: [ '${{ secrets.matlab_license_r2019a }}' ]
        mysql_version: ["8.0.18", "5.7", "5.6"]
        include:
          - matlab_version: "R2018b"
            matlab_license: ${{ secrets.matlab_license_r2018b }}
            mysql_version: "5.7"
          - matlab_version: "R2016b"
            matlab_license: ${{ secrets.matlab_license_r2016b }}
            mysql_version: "5.7"
    steps:
      - uses: actions/checkout@v2
      - name: Run primary tests
        env:
          MATLAB_UID: "1001"
          MATLAB_GID: "116"
          MATLAB_USER: ${{ secrets.matlab_user }}
          MATLAB_HOSTID: ${{ secrets.matlab_hostid }}
          MATLAB_VERSION: ${{ matrix.matlab_version }}
          MYSQL_TAG: ${{ matrix.mysql_version }}
          MATLAB_LICENSE: ${{ matrix.matlab_license }}
          DOCKER_CLIENT_TIMEOUT: "120"
          COMPOSE_HTTP_TIMEOUT: "120"
        run: |
          docker-compose -f LNX-docker-compose.yml up --build --exit-code-from app
